title = 'STARFALL'
baseURL = 'https://starfall.community/'
languageCode = 'en-us'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "G-TSH75V2ZCY"
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
general = '/general/:year/:month/:title'
world-of-warcraft = '/world-of-warcraft/:year/:month/:title'
tags = '/tag/:title'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-black"
  recent_posts_number = 3
  custom_css = ["db_sans.css"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
