baseURL = 'https://starfall.community/'
languageCode = 'en-us'
title = 'STARFALL'
theme = 'ananke'
sectionPagesMenu = 'main'

[markup]

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[menu]

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 1

